name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:

jobs:
  docker_hub:
    name: Docker Hub
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: ${{ github.event.repository.name }}
    secrets: inherit

  staging:
    name: Staging
    needs: [docker_hub]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Staging
      github_environment_url: https://patterns.staging.hypothes.is
      aws_region: us-west-1
      elasticbeanstalk_application: frontend-shared
      elasticbeanstalk_environment: staging
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit

  production:
    name: Production
    needs: [docker_hub, staging]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production
      github_environment_url: https://patterns.hypothes.is
      aws_region: us-west-1
      elasticbeanstalk_application: frontend-shared
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.Docker_Hub.outputs.docker_tag }}
    secrets: inherit
